config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'


  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  get "/eventos" => 'events#new', :as => :new_event 
  post "/eventos" => 'events#create', :as => :create_events 
  get "/habitaciones/:permalink" => 'frontend#show_room' , :as => :show_room
  get "/restaurantes" => "frontend#restaurants" , as: :restaurants

  get "/reservaciones" => 'reservations#new' , as: :new_reservation
  post "/reservaciones" => 'reservations#create' , as: :create_reservation

  scope :admin do
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :rooms do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :clients do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :reservations, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :events, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    
  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'


end

app/models/event.rb
#Generado por keppler
require 'elasticsearch/model'
class Event < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  belongs_to :client
  accepts_nested_attributes_for :client
  before_validation :verify_client

  validates_presence_of :begin_date, :end_date, :event_type

  #validacion de cantidad de personas
  validates :quantity, :numericality => { :less_than_or_equal_to => 100 }

  #custom validate
  validate :end_date_greater_than_begin_date?
  validate :assembly_type_not_blank

  after_commit on: [:update] do
    __elasticsearch__.index_document
  end

  def chosen(selection)
    if selection == true
      return "Si"
    else
      return "No"
    end
  end

  def blank(text)
    if text.blank?
      return "N/A"
    end
  end

  def end_date_greater_than_begin_date?
    unless self.begin_date.blank? or self.end_date.blank?
      errors.add(:base, "La fecha de inicio no puede ser despues de la fecha de fin") if self.begin_date > self.end_date
    end
  end

  def assembly_type_not_blank
    errors.add(:base, 'Debe seleccionar un tipo de montaje') unless self.assembly_type
  end

  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:date_event, :event_type, :quantity, :begin_date, :end_date, :begin_time, :end_time, :assembly_type, :event_description, :client_name, :client_documentation, :client_telephone, :client_email, :client_company] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      client_name: self.client.name,
      client_documentation: self.client.documentation,
      client_telephone: self.client.telephone,
      client_email: self.client.email,
      client_company: self.client.company,
      date_event: self.date_event.to_s,
      event_type: self.event_type,
      quantity: self.quantity.to_s,
      begin_date: self.begin_date.to_s,
      end_date: self.end_date.to_s,
      begin_time: self.begin_time.to_s,
      end_time: self.end_time.to_s,
      assembly_type: self.assembly_type,
      event_description: self.event_description,
    }.as_json
  end

  #Se buscó el modelo "Client" por ActiveRecord ya que "Client" es un módulo reservado por ElasticSearch
  def verify_client
    if self.client.valid?
      client = ActiveRecord::Base.descendants.select { |model| model.to_s == "Client" } .first.find_by_documentation(self.client.documentation)

      if client
        client.update_attributes self.client.as_json only: [:name, :company, :email, :telephone]
        self.client = client
      end
    end
  end

  def status(begin_date, end_date)
    begin_date = Date.parse(begin_date)
    end_date = Date.parse(end_date)
    time_now = Date.parse(Time.new.to_s)

    if  time_now < begin_date
      return "#DC7B31"
    elsif time_now >= begin_date and time_now <= end_date
      return "#0ABB33"
    else
      return "#EC0B0B"
    end
  end

end
#Event.import

app/controllers/events_controller.rb
#Generado con Keppler.
class EventsController < ApplicationController  
  before_filter :authenticate_user!, except: [:new, :create]
  layout :resolve_layout
  load_and_authorize_resource except: [:new, :create]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  def index
    events = Event.searching(@query).all
    @objects, @total = events.page(@current_page), events.size
    redirect_to events_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.client = Client.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    params[:event].parse_time_select!(:begin_time)
    params[:event].parse_time_select!(:end_time)
    if !event_params[:begin_time].to_s.empty? && !event_params[:end_time].to_s.empty?
      params[:event][:begin_time] = params[:event][:begin_time].strftime("%I:%M %p")
      params[:event][:end_time] = params[:event][:end_time].strftime("%I:%M %p")
    end
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        EventMailer.event_admin(@event).deliver_now
        EventMailer.event_user(@event).deliver_now
        format.html { redirect_to root_path, notice: @event.client.name+', La solicitud de reserva para su evento ya ha sido enviada.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  def destroy_multiple
    Event.destroy redefine_ids(params[:multiple_ids])
    redirect_to events_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:date_event, :event_type, :quantity, :begin_date, :end_date, :begin_time, :end_time, :assembly_type, :event_description, :cold_snacks, :hot_snacks, :dish_menu, :buffet_type, :theme_stations, :morning_coffeebreak, :evening_coffeebreak, :cheese_table, :uncorking_coctels, :uncorking_whisky, :uncorking_wine, :uncorking_vodka, :coctel_bar, :sodas, :color_theme, :flower_arrengements, :baloons, :toldo, :sound, :dj, :musical_group, :podium, :videobeam, :lights, :inflatable, :magic_show, :dance_show, :crazy_hour, :other_services, :observations, client_attributes: [:name, :documentation, :company, :telephone, :email])
    end
    
    def resolve_layout
      case action_name
      when "destroy", "update", "edit", "show", "index"
        'admin/application'
      else
        'frontend/application'
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
.banner#banner-events

#form-reservation

  - unless @event.errors[:base].empty?
    %div.alert.alert-danger.form-alert{ onclick: "hideFormAlert();" }
      %div
        Para continuar debe llenar correctamente el formulario.
        - @event.errors[:base].each_with_index do |e,i|
          - if i <= 4
            %p{style: 'margin-bottom: 0;'}= "- #{e}"

  .container-bamboo
    .container.contacto-container

      = simple_form_for @event, url: create_events_path do |f|
        .row
          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            .title-form
              %a DATOS PERSONALES
            = f.simple_fields_for :client do |c|
              .col-lg-6.col-md-6.col-sm-6.col-xs-12
                .field
                  = c.input :name, label: false, :placeholder=> "NOMBRE Y APELLIDO (REQUERIDO)"
              .col-lg-6.col-md-6.col-sm-6.col-xs-12
                .field
                  = c.input :documentation, label: false, :placeholder=> "CÉDULA/RIF (REQUERIDO)"
              .col-lg-6.col-md-6.col-sm-6.col-xs-12
                .field
                  = c.input :company, label: false, :placeholder=> "NOMBRE DE LA EMPRESA"
              .col-lg-6.col-md-6.col-sm-6.col-xs-12
                .field
                  = c.input :email, label: false, :placeholder=> "CORREO ELECTRÓNICO"
              .col-lg-6.col-md-6.col-sm-6.col-xs-12
                .field
                  = c.input :telephone, label: false, :placeholder=> "TELÉFONO"
              .col-lg-6.col-md-6.col-sm-6.col-xs-12
                .field
                  = f.input :date_event, label: false, :placeholder=> "FECHA DEL EVENTO" , as: :string, input_html: {class: "datepicker"}

          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            .title-form
              %a DATOS DEL EVENTO
            .col-lg-3.col-md-3.col-sm-3.col-xs-12
              .field
                = f.input :event_type, label: false, :placeholder=> "TIPO DE EVENTO"
            .col-lg-3.col-md-3.col-sm-3.col-xs-12
              .field
                = f.input :color_theme, label: false, :placeholder=> "COLORES/MOTIVO"
            .col-lg-6.col-md-6.col-sm-6.col-xs-12
              .field
                = f.input :quantity, label: false, :placeholder=> "CANTIDAD DE PERSONAS"

            .col-lg-3.col-md-3.col-sm-6.col-xs-6
              = f.input :begin_date, label: false, placeholder: "FECHA DE INICIO", as: :string, input_html: {class: "datepicker", id: "checkin" }
            .col-lg-3.col-md-3.col-sm-6.col-xs-6
              = f.input :end_date, label: false, placeholder: "FECHA DE FIN", as: :string, input_html: {class: "datepicker", id: "checkout"}
            .col-lg-3.col-md-3.col-sm-6.col-xs-6
              .field
                = f.time_select :begin_time, { :combined => true, prompt: "HORA DE INICIO", :minute_interval => 30,:time_separator => "",:start_hour => 0,:start_minute => 0,:end_hour => 23, :end_minute => 0, ampm: true  }, { class: "select_time" }
            .col-lg-3.col-md-3.col-sm-6.col-xs-6
              .field
                = f.time_select :end_time, { :combined => true, prompt: "HORA DE FIN", :minute_interval => 30,:time_separator => "",:start_hour => 0,:start_minute => 0,:end_hour => 23, :end_minute => 0, ampm: true }, { class: "select_time" }
            %br.hidden-xs.hidden-md
            %br.hidden-xs.hidden-md
            %br.hidden-xs.hidden-md
            %br.hidden-xs.hidden-md
            %br.hidden-xs.hidden-md

          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            .title-form
              %a TIPO DE MONTAJE
            .btn-group{"data-toggle" => "buttons"}
              %center
                .col-lg-2.col-md-2.col-sm-4.col-xs-12
                  %label.btn.btn-montaje
                    %center
                      #image-montaje-1
                        = f.radio_button :assembly_type, "Auditorio"
                    %p Auditorio
                .col-lg-2.col-md-2.col-sm-4.col-xs-12
                  %label.btn.btn-montaje
                    %center
                      #image-montaje-2
                        = f.radio_button :assembly_type, "Reunion"
                    %p Reunión
                .col-lg-2.col-md-2.col-sm-4.col-xs-12
                  %label.btn.btn-montaje
                    %center
                      #image-montaje-3
                        = f.radio_button :assembly_type, "Tipo 'U'"
                    %p Tipo 'U'
                .col-lg-2.col-md-2.col-sm-4.col-xs-12
                  %label.btn.btn-montaje
                    %center
                      #image-montaje-4
                        = f.radio_button :assembly_type, "Banquete"
                    %p Banquete
                .col-lg-2.col-md-2.col-sm-4.col-xs-12
                  %label.btn.btn-montaje
                    %center
                      #image-montaje-5
                        = f.radio_button :assembly_type, "Escuela"
                    %p Escuela
                .col-lg-2.col-md-2.col-sm-4.col-xs-12
                  %label.btn.btn-montaje
                    %center
                      #image-montaje-6
                        = f.radio_button :assembly_type, "Coctel"
                    %p Coctel
            .col-lg-12.col-md-12.col-sm-12.col-xs-12
              .field
                = f.text_area :event_description, :placeholder=> "DESCRIPCIÓN DE EVENTO", style: "margin-bottom: 0;"
          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            .title-form
              %a ALIMENTOS & BEBIDAS:
            .col-lg-3.col-md-4.col-sm-6.col-xs-12
              .field
                %label.btn.btn-check
                  = f.check_box :cold_snacks
                  %p
                    %label Pasapalos Frios
            .col-lg-3.col-md-4.col-sm-6.col-xs-12
              .field
                %label.btn.btn-check
                  = f.check_box :hot_snacks
                  %p
                    %label Pasapalos Calientes
            .col-lg-3.col-md-4.col-sm-6.col-xs-12
              .field
                %label.btn.btn-check
                  = f.check_box :dish_menu
                  %p
                    %label Menú Plateado
            .col-lg-3.col-md-4.col-sm-6.col-xs-12
              .field
                %label.btn.btn-check
                  = f.check_box :theme_stations
                  %p
                    %label Estaciones Temáticas
            .col-lg-3.col-md-4.col-sm-6.col-xs-12
              .field
                %label.btn.btn-check
                  = f.check_box :buffet_type
                  %p
                    %label Tipo Buffet
            .col-lg-3.col-md-4.col-sm-6.col-xs-12
              .field
                %label.btn.btn-check
                  = f.check_box :morning_coffeebreak
                  %p
                    %label Coffee Break Matutino
            .col-lg-3.col-md-4.col-sm-6.col-xs-12
              .field
                %label.btn.btn-check
                  = f.check_box :evening_coffeebreak
                  %p
                    %label Coffee Break Vespertino
            .col-lg-3.col-md-4.col-sm-6.col-xs-12
              .field
                %label.btn.btn-check
                  = f.check_box :cheese_table
                  %p
                    %label Mesa de Quesos
            .col-lg-3.col-md-4.col-sm-6.col-xs-12
              .field
                %label.btn.btn-check
                  = f.check_box :uncorking_coctels
                  %p
                    %label Descorche de Cocteles
            .col-lg-3.col-md-4.col-sm-6.col-xs-12
              .field
                %label.btn.btn-check
                  = f.check_box :uncorking_whisky
                  %p
                    %label Descorche de Whisky
            .col-lg-3.col-md-4.col-sm-6.col-xs-12
              .field
                %label.btn.btn-check
                  = f.check_box :uncorking_wine
                  %p
                    %label Des. Vino/Champagne
            .col-lg-3.col-md-4.col-sm-6.col-xs-12
              .field
                %label.btn.btn-check
                  = f.check_box :uncorking_vodka
                  %p
                    %label Des. Vodka/Ron
            .col-lg-3.col-md-4.col-sm-6.col-xs-12
              .field
                %label.btn.btn-check
                  = f.check_box :coctel_bar
                  %p
                    %label Barra Coctelera
            .col-lg-3.col-md-4.col-sm-6.col-xs-12
              .field
                %label.btn.btn-check
                  = f.check_box :sodas
                  %p
                    %label Refrescos
          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            .title-form
              %a DECORACIÓN DEL EVENTO:
            .row
              .col-lg-3.col-md-4.col-sm-4.col-xs-12
                .field
                  %label.btn.btn-check
                    = f.check_box :flower_arrengements
                    %p
                      %label Arreglos Florales
              .col-lg-3.col-md-4.col-sm-4.col-xs-12
                .field
                  %label.btn.btn-check
                    = f.check_box :baloons
                    %p
                      %label Globos
              .col-lg-3.col-md-4.col-sm-4.col-xs-12
                .field
                  %label.btn.btn-check
                    = f.check_box :toldo
                    %p
                      %label Toldo
              .col-lg-3.col-md-4.col-sm-6.col-xs-12
                .field
                  %label.btn.btn-check
                    = f.check_box :sound
                    %p
                      %label Sonido
              .col-lg-3.col-md-4.col-sm-6.col-xs-12
                .field
                  %label.btn.btn-check
                    = f.check_box :dj
                    %p
                      %label Dj
              .col-lg-3.col-md-4.col-sm-6.col-xs-12
                .field
                  %label.btn.btn-check
                    = f.check_box :musical_group
                    %p
                      %label Grupo Musical
              .col-lg-3.col-md-4.col-sm-6.col-xs-12
                .field
                  %label.btn.btn-check
                    = f.check_box :podium
                    %p
                      %label Podium
              .col-lg-3.col-md-4.col-sm-6.col-xs-12
                .field
                  %label.btn.btn-check
                    = f.check_box :videobeam
                    %p
                      %label Videobeam
              .col-lg-3.col-md-4.col-sm-6.col-xs-12
                .field
                  %label.btn.btn-check
                    = f.check_box :lights
                    %p
                      %label Iluminación
              .col-lg-3.col-md-4.col-sm-6.col-xs-12
                .field
                  %label.btn.btn-check
                    = f.check_box :inflatable
                    %p
                      %label Inflables
              .col-lg-3.col-md-4.col-sm-6.col-xs-12
                .field
                  %label.btn.btn-check
                    = f.check_box :magic_show
                    %p
                      %label Show de Magia
              .col-lg-3.col-md-4.col-sm-6.col-xs-12
                .field
                  %label.btn.btn-check
                    = f.check_box :dance_show
                    %p
                      %label Show de Baile
              .col-lg-3.col-md-4.col-sm-6.col-xs-12
                .field
                  %label.btn.btn-check
                    = f.check_box :crazy_hour
                    %p
                      %label Hora Loca
            %br
            %br
            .col-lg-6.col-md-6.col-sm-6.col-xs-12
              .title-form
                %a OTROS SERVICIOS
              .field
                = f.text_area :other_services, id: 'textarea-6'
            .col-lg-6.col-md-6.col-sm-6.col-xs-12
              .title-form
                %a OBSERVACIONES
              .field
                = f.text_area :observations, id: 'textarea-6'
            .form-actions
              = f.button :submit, "RESERVAR", class: "btn btn-save", id: "btn-submit" , style: "width: auto;"

app/views/events/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Event
			= link_to edit_event_path(@event), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @event.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @event.client.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.email")
			.display-value= @event.client.email
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.telephone")
			.display-value= @event.client.telephone
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.quantity")
			.display-value= "#{@event.quantity} Personas"
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.event_type")
			.display-value= @event.event_type.humanize
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.begin_date")
			.display-value= @event.begin_date
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.end_date")
			.display-value= @event.end_date
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.assembly_type")
			.display-value= @event.assembly_type
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/events/_listing.html.haml
%tr{ id: "row-#{event.id}" }
	- if can? :destroy_multiple, Event
		%td.item-check{style:"width: 10%"}
			= link_to "", event_path(event), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{event.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{event.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{event.id}" }

		%td{style: "color: #{event.status(event.begin_date, event.end_date)}"}
			= material_icon.md_24.access_time

		%td{style:"width: 30%"}
			= link_to "", event_path(event, search: @query), remote: true, class: "show-row"
			%span
				= event.client.name
		%td{style:"width: 30%"}
			= link_to "", event_path(event, search: @query), remote: true, class: "show-row"
			%span
				= event.client.company
		%td{style:"width: 30%"}
			= link_to "", event_path(event, search: @query), remote: true, class: "show-row"
			%span
				= event.date_event
		%td{style:"width: 30%"}
			= link_to "", event_path(event, search: @query), remote: true, class: "show-row"
			%span
				= "#{event.quantity} Personas"
								 
	%td{style:"width: 5%"}		
		= link_to event_path(event), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/events/new.html.haml
= title "Nuevo Evento"
= render 'form'

app/views/events/show.html.haml
= title "events | #{@event.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Event
				= link_to event_path(@event), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Event
				= link_to edit_event_path(@event), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to events_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.panel-body#body-show.order-event-show
			.container
				%table.table.table-bordered
					%tr
						%th Nombre
						%th Cedula/rif
						%th Empresa
						%th Fecha de Solicitud
						%th Email
						%th Teléfono
					%tr
						%td= @event.client.name.humanize
						%td= @event.client.documentation
						%td= @event.client.company.humanize
						%td= @event.date_event
						%td= @event.client.email.downcase
						%td= @event.client.telephone
					%tr
						%th{colspan: "3"} Tipo de evento
						%th{colspan: "3"} Colores/motivo
					%tr
						%td{colspan: "3"}= @event.event_type.humanize
						%td{colspan: "3"}= @event.color_theme.humanize
					%tr
						%th N° de Invitados
						%th Fecha de Inicio
						%th Fecha de Culminación
						%th Hora de Inicio
						%th Hora de Culminación
						%th Tipo de Montaje
					%tr
						%td= "#{@event.quantity} Personas"
						%td= @event.begin_date
						%td= @event.end_date
						%td= @event.begin_time
						%td= @event.end_time
						%td= @event.assembly_type
					%tr
						%th{colspan: "6"} Descripción del evento
					%tr
						%td{colspan: "6"}= @event.blank(@event.event_description)
					%tr
						%th{colspan: "6"} Alimentos & Bebidas
					%tr
						%th Pasapalos Fríos
						%th Pasapalos Caliente
						%th Menú Plateado
						%th Estaciones Temáticas
						%th Tipo Buffet
						%th Coffee Break Matutino
					%tr
						%td
							%center= @event.chosen(@event.cold_snacks)
						%td
							%center= @event.chosen(@event.hot_snacks)
						%td
							%center= @event.chosen(@event.dish_menu)
						%td
							%center= @event.chosen(@event.theme_stations)
						%td
							%center= @event.chosen(@event.buffet_type)
						%td
							%center= @event.chosen(@event.morning_coffeebreak)
					%tr
						%th Coffee Break Vespertino
						%th Mesa de Quesos
						%th Descorche de Cocteles
						%th Descorche de Whisky
						%th Descorche de Vino/Champagne
						%th Descorche de Vodka/Ron
					%tr
						%td
							%center= @event.chosen(@event.evening_coffeebreak)
						%td
							%center= @event.chosen(@event.cheese_table)
						%td
							%center= @event.chosen(@event.uncorking_coctels)
						%td
							%center= @event.chosen(@event.uncorking_whisky)
						%td
							%center= @event.chosen(@event.uncorking_wine)
						%td
							%center= @event.chosen(@event.uncorking_vodka)
					%tr
						%th Barra Coctelera
						%th Refrescos
						%th{colspan: "4", rowspan: "2"}
					%tr
						%td
							%center= @event.chosen(@event.coctel_bar)
						%td
							%center= @event.chosen(@event.sodas)
					%tr
						%th
					%tr
						%th Arreglos Florales
						%th Globos
						%th Toldo
						%th Sonido
						%th Dj
						%th Grupo Musical
					%tr
						%td
							%center= @event.chosen(@event.flower_arrengements)
						%td
							%center= @event.chosen(@event.baloons)
						%td
							%center= @event.chosen(@event.toldo)
						%td
							%center= @event.chosen(@event.sound)
						%td
							%center= @event.chosen(@event.dj)
						%td
							%center= @event.chosen(@event.musical_group)
					%tr
						%th Podium
						%th Videobeam
						%th Iluminación
						%th Inflables
						%th Show de Magia
						%th Show de Baile
					%tr
						%td
							%center= @event.chosen(@event.podium)
						%td
							%center= @event.chosen(@event.videobeam)
						%td
							%center= @event.chosen(@event.lights)
						%td
							%center= @event.chosen(@event.inflatable)
						%td
							%center= @event.chosen(@event.magic_show)
						%td
							%center= @event.chosen(@event.dance_show)
					%tr
						%th Hora Loca
						%th{colspan: "5", rowspan: "2"}
					%tr
						%td
							%center= @event.chosen(@event.crazy_hour)
					%tr
						%th{colspan: "6"} Otros Servicios
					%tr
						%td{colspan: "6"}= @event.blank(@event.other_services)
					%tr
						%th{colspan: "6"} Observaciones Adicionales
					%tr
						%td{colspan: "6"}= @event.blank(@event.observations)