config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'


  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  get "/eventos" => 'events#new', :as => :new_event 
  post "/eventos" => 'events#create', :as => :create_events 
  get "/habitaciones/:permalink" => 'frontend#show_room' , :as => :show_room
  get "/restaurantes" => "frontend#restaurants" , as: :restaurants

  get "/reservaciones" => 'reservations#new' , as: :new_reservation
  post "/reservaciones" => 'reservations#create' , as: :create_reservation

  scope :admin do
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :rooms do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :clients do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :reservations, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :events, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    
  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'


end

app/models/reservation.rb
#Generado por keppler
require 'elasticsearch/model'
class Reservation < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  has_many :rooms, through: :orders
  has_many :orders
  belongs_to :client
  accepts_nested_attributes_for :orders, :reject_if => :all_blank, :allow_destroy => true
  validates_presence_of :adults, :checkin, :checkout
  validate :validates_rooms, :validate_fields, :valid_check_in, :valid_date_range_required, :orders_filter
  accepts_nested_attributes_for :client
  before_validation :verify_client

  after_commit on: [:update] do
    __elasticsearch__.index_document
  end

  def self.searching(query)
    if query
      self.search(self.query(query)).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:origin, :motive, :checkin, :checkout, :payment, :client_name, :client_documentation, :client_telephone, :client_email], operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      client_name: self.client.name,
      client_documentation: self.client.documentation,
      client_telephone: self.client.telephone,
      client_email: self.client.email,
      adults: self.adults.to_s,
      kids: self.kids.to_s,
      babies: self.babies.to_s,
      origin: self.origin,
      motive: self.motive,
      checkin:  self.checkin.strftime("%d-%m-%Y"),
      checkout:  self.checkout.strftime("%d-%m-%Y"),
      payment:  self.payment.to_s,
      observations:  self.observations
    }.as_json
  end

  def reservation_days
    (self.checkout.to_date - self.checkin.to_date).to_i
  end

  def total_price_for_night
    self.orders.inject(0){ |total, item | total += item.quantity.to_i * item.room.price.to_i }
  end

  def price_total
    self.total_price_for_night*reservation_days
  end

  def orders_filter
    self.orders.each do |order|
      if order.quantity.blank?
        self.orders.delete(order)
      end
    end
  end

  def valid_date_range_required
    unless self.checkin.blank? or self.checkout.blank?
      errors.add(:base, "El check-out no puede ser despues del check-in") if self.checkin > self.checkout
    end
  end

  def valid_check_in
    unless self.checkin.blank? or self.checkout.blank?
      errors.add(:base, "El check-in que usted ingresó no es valido") if self.checkin < Date.parse(Time.new.to_s)
      errors.add(:base, "El check-in que usted ingresó no es valido") if self.checkout < Date.parse(Time.new.to_s)
    end
  end

  def validates_rooms
    room_hash = []
    self.orders.each do |order|
      unless order.quantity.blank?
        room_hash << order.quantity
      end
    end
    if room_hash.blank?
      errors.add(:base, "Debe elegir una habitación")
    end
  end

  def validate_fields
    errors.add(:base, "Debe elegir una forma de pago") if self.payment == 0
    errors.add(:base, "El N° de Niños debe ser mayor a cero") if self.kids.to_i < 0
    errors.add(:base, "El N° de Bebés debe ser mayor a cero") if self.babies.to_i < 0
    errors.add(:base, "El N° de Adultos debe ser mayor a cero") if self.adults.to_i < 1
  end

  #Se buscó el modelo "Client" por ActiveRecord ya que "Client" es un módulo reservado por ElasticSearch
  def verify_client
    if self.client.valid?
      client = ActiveRecord::Base.descendants.select { |model| model.to_s == "Client" } .first.find_by_documentation(self.client.documentation)

      if client
        client.update_attributes self.client.as_json only: [:name, :company, :email, :telephone]
        self.client = client
      end
    end
  end

  def status(checkin, checkout)
    checkin = Date.parse(checkin)
    checkout = Date.parse(checkout)
    time_now = Date.parse(Time.new.to_s)

    if  time_now < checkin
      return "#DC7B31"
    elsif time_now >= checkin and time_now <= checkout
      return "#0ABB33"
    else
      return "#EC0B0B"
    end
  end

end
#Reservation.import

app/controllers/reservations_controller.rb
#Generado con Keppler.
class ReservationsController < ApplicationController
  before_filter :authenticate_user!, except: [:new, :create]
  layout :resolve_layout
  load_and_authorize_resource except: [:new, :create]
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  def index
    reservations = Reservation.searching(@query).all
    @objects, @total = reservations.page(@current_page), reservations.size
    redirect_to reservations_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /reservations/1
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new(checkin: params[:checkin], checkout: params[:checkout])
    @reservation.client = Client.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  def create
    @reservation = Reservation.new(reservation_params)
    respond_to do |format|
      if @reservation.save
        ReservationMailer.reservation_admin(@reservation).deliver_now
        ReservationMailer.reservation_user(@reservation).deliver_now
        format.html { redirect_to root_path, notice: @reservation.client.name+', La solicitud de reserva ya ha sido enviada.' }
        format.json { render action: 'show', status: :created, location: @reservation }
      else
        format.html { render action: 'new' }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  def update
    if @reservation.update(reservation_params)
      redirect_to @reservation, notice: 'Reservation was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /reservations/1
  def destroy
    @reservation.destroy
    redirect_to reservations_url, notice: 'Reservation was successfully destroyed.'
  end

  def destroy_multiple
    Reservation.destroy redefine_ids(params[:multiple_ids])
    redirect_to reservations_path(page: @current_page, search: @query), notice: "Reservaciones eliminados satisfactoriamente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def reservation_params
      params.require(:reservation).permit(:adults, :kids, :babies, :origin, :motive, :checkin, :checkout, :payment, :observations, orders_attributes: [:id, :room_id, :quantity, :_destroy], client_attributes: [:name, :documentation, :telephone, :email])
    end

    def resolve_layout
      case action_name
      when "destroy", "update", "edit", "show", "index"
        'admin/application'
      else
        'frontend/application'
      end
    end

end

app/views/reservations/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Aquí podrá gestionar todos las reservaciones solicitadas mediante la web. Ofrece opciones para visualizar y eliminar  las solicitudes.

app/views/reservations/_form.html.haml
.banner#banner-reserva

#form-reservation

  - unless @reservation.errors[:base].empty?
    %div.alert.alert-danger.form-alert{ onclick: "hideFormAlert();" }
      %div
        Para continuar debe llenar correctamente el formulario.
        - @reservation.errors[:base].each_with_index do |e,i|
          - if i <= 4
            %p{style: 'margin-bottom: 0;'}= "- #{e}"

  = simple_form_for @reservation, url: new_reservation_path  do |f|
    .title-form
      %a Datos personales
    = f.simple_fields_for :client do |c|
      .col-lg-6.col-md-6.col-sm-6.col-xs-12
        .field
          = c.input :name, label: false, :placeholder=> "Nombre y Apellido (Requerido)"
      .col-lg-6.col-md-6.col-sm-6.col-xs-12
        .field
          = c.input :documentation, label: false, :placeholder=> "Cédula/RIF (Requerido)"
      .col-lg-6.col-md-6.col-sm-6.col-xs-12
        .field
          = c.input :email, label: false, :placeholder=> "Correo electrónico"
      .col-lg-6.col-md-6.col-sm-6.col-xs-12
        .field
          = c.input :telephone, label: false, :placeholder=> "Teléfono"

    .title-form
      %a Datos de reservación

    .row
      .col-lg-4.col-md-4.col-sm-12.col-xs-12
        .col-lg-12.col-md-12.col-sm-4.col-xs-4
          = f.input :adults, label: false, placeholder: "N° Adultos", input_html: { min: 0 }
        .col-lg-6.col-md-6.col-sm-4.col-xs-4
          = f.input :kids, label: false, placeholder: "N° Niños", input_html: { min: 0 }
        .col-lg-6.col-md-6.col-sm-4.col-xs-4
          = f.input :babies, label: false, placeholder: "N° Bebés", input_html: { min: 0 }
      .col-lg-4.col-md-4.col-sm-12.col-xs-12
        .col-lg-12.col-md-12.col-sm-6.col-xs-6
          = f.input :checkin, label: false, placeholder: "Check-in", as: :string, input_html: {class: "datepicker", id: "checkin" }
        .col-lg-12.col-md-12.col-sm-6.col-xs-6
          = f.input :checkout, label: false, placeholder: "Check-out", as: :string, input_html: {class: "datepicker", id: "checkout"}
      .col-lg-4.col-md-4.col-sm-12.col-xs-12
        = f.input :origin, label: false, placeholder: "Procedencia"
        = f.input :motive, label: false, placeholder: "Motivo"

    .title-form
      %a Tipo de habitación

    .row{style: ""}
      - Room.all.each_with_index do |room, i|
        .room-checks.col-lg-2.col-md-2.col-sm-6.col-xs-6
          = f.simple_fields_for :orders, @reservation.orders.build do |r|
            %a.btn.btn-room{onclick: "quantity(#{room.id})"}
              #image-room{class: "check-#{room.name}", style: "background-image: url(#{room.cover});"}
                = r.input :room_id, label: false, :collection => [[room.name, room.id]], :as => :check_boxes, include_hidden: false, input_html: { name: "reservation[orders_attributes][#{room.id}][room_id]", id: "reservation_orders_attributes_#{room.id}_room_id_#{room.id}"}
              .image-room-mask{id: "mask-#{room.id}"}
                %p
                  = room.name
            .quantity{id: "id-#{room.id}"}
              = r.input :quantity, label:false, placeholder: "Cantidad", input_html: {name: "reservation[orders_attributes][#{room.id}][quantity]"}
            .room-price{id: "price-#{room.id}"}
              = room.price
              Bs
    .row
      .col-lg-6.col-md-6.col-sm-6.col-xs-12
        .box-form
          .title-form{style: "padding-top: 0;"}
            %a Total de reserva
          .content-box#total
            %table
              %tbody
                %tr
                  %td
                    Número de habitaciones:
                  %td#num-rooms
                    0
                %tr
                  %td
                    Precio total (Por noche):
                  %td#price-night
                    0 Bs
                %tr
                  %td
                    Total a pagar:
                  %td#price-total
                    0 Bs
          .content-box{style: "margin-top: 10px;"}
            = f.input :payment, as: :select, include_blank: false, collection: [["Tipo de pago", "0"], ["Tarjeta de crédito","1"], ["Deposito y/o Transferencia", "2"], ["Efectivo","3"]], label: false

      .col-lg-6.col-md-6.col-sm-6.col-xs-12
        .box-form
          .title-form{style: "padding-top: 0;"}
            %a Observaciones
          = f.input :observations, label: false, placeholder: 'Observaciones'
          .note
            %span Nota:
            *Los precios que se muestran son para ocupación de una (1) persona en habitación sencilla y (2) dos personas en habitación: estándar, doble y suite de luxe. Se hace recargo por cada persona adicional niño o adulto.*

    .form-actions
      = f.button :submit, "Guardar", class: "btn btn-save", id: "btn-submit" , style: "width: auto;", controller: "reservation", action: "create"

:javascript
  $('#btn-submit').click(function(){
    setTimeout("$('#btn-submit').prop('disabled', 'disabled')", 10);
  });

app/views/reservations/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Reservation
			= link_to edit_reservation_path(@reservation), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @reservation.client.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.documentation")
			.display-value= @reservation.client.documentation
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.email")
			.display-value= @reservation.client.email
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.telephone")
			.display-value= @reservation.client.telephone
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.checkin")
			.display-value= @reservation.checkin.strftime("%d-%m-%Y")
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.checkout")
			.display-value= @reservation.checkout.strftime("%d-%m-%Y")
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.adults")
			.display-value= @reservation.adults
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.kids")
			.display-value= (@reservation.kids.blank? or @reservation.kids.zero?) ? "N/A" : @reservation.kids
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.babies")
			.display-value= (@reservation.babies.blank? or @reservation.babies.zero?) ? "N/A" : @reservation.babies
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.origin")
			.display-value= @reservation.origin
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.motive")
			.display-value= @reservation.motive
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.payment")
			- if @reservation.payment == 1
				.display-value Tarjeta de crédito
			- elsif @reservation.payment == 2
				.display-value Depósito o Transferencia
			- else 
				.display-value Efectivo
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.observations")
			.display-value= @reservation.observations.blank? ? "N/A" : @reservation.observations
	
:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/reservations/_listing.html.haml
%tr{ id: "row-#{reservation.id}" }
	- if can? :destroy_multiple, Reservation
		%td.item-check{style:"width: 10%"}
			= link_to "", reservation_path(reservation), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{reservation.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{reservation.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{reservation.id}" }
		
		%td{style: "color: #{reservation.status(reservation.checkin.strftime("%d-%m-%Y"), reservation.checkout.strftime("%d-%m-%Y"))}"}
			= material_icon.md_24.access_time

		%td
			= link_to "", reservation_path(reservation, search: @query), remote: true, class: "show-row"
			%span
				= reservation.client.name
		%td.hide-on-small-and-down
			= link_to "", reservation_path(reservation, search: @query), remote: true, class: "show-row"
			%span
				= reservation.client.documentation
		%td.hide-on-small-and-down
			= link_to "", reservation_path(reservation, search: @query), remote: true, class: "show-row"
			%span
				= reservation.client.telephone
		%td
			= link_to "", reservation_path(reservation, search: @query), remote: true, class: "show-row"
			%span
				= reservation.created_at.strftime("%d-%m-%Y")
								
	%td{style:"width: 5%"}		
		= link_to reservation_path(reservation), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/reservations/index.html.haml
= title("Reservaciones - Listado")
.listing.col.l9.m12.s12
	
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |reservation|
				= render 'listing', reservation: reservation
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado reservaciones.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

app/views/reservations/new.html.haml
= title "Nueva Reservación"

= render 'layouts/frontend/navigation'
= render 'form'

app/views/reservations/show.html.haml
= title "Reservaciones | #{@reservation.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Reservation
				= link_to reservation_path(@reservation), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: '¿Está seguro de querer eliminar?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			= link_to reservations_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		
		.panel-body#body-show.order-event-show
			.container
				%table.table.table-bordered
					%tr
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.name")
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.email")
					%tr
						%td{ colspan: '2' }
							= @reservation.client.name
						%td{ colspan: '2' }
							= @reservation.client.email
					%tr
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.documentation")
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.telephone")
					%tr
						%td{ colspan: '2' }
							= @reservation.client.documentation
						%td{ colspan: '2' }
							= @reservation.client.telephone
					%tr
						%th{ colspan: '1' }
							= t("model.#{controller_name.singularize}.attributes.adults")
						%th{ colspan: '1' }
							= t("model.#{controller_name.singularize}.attributes.kids")
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.babies")
					%tr
						%td{ colspan: '1' }
							= @reservation.adults
						%td{ colspan: '1' }
							= (@reservation.kids.blank? or @reservation.kids.zero?) ? "N/A" : @reservation.kids
						%td{ colspan: '2' }
							= (@reservation.babies.blank? or @reservation.babies.zero?) ? "N/A" : @reservation.babies
					%tr
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.origin")
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.motive")
					%tr
						%td{ colspan: '2' }
							= @reservation.origin
						%td{ colspan: '2' }
							= @reservation.motive
					%tr
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.checkin")
						%th{ colspan: '2' }
							= t("model.#{controller_name.singularize}.attributes.checkout")
					%tr
						%td{ colspan: '2' }
							= @reservation.checkin.strftime("%d-%m-%Y")
						%td{ colspan: '2' }
							= @reservation.checkout.strftime("%d-%m-%Y")
					%tr
						%th{ colspan: '4' }
							= t("model.#{controller_name.singularize}.attributes.payment")
					%tr
						%td{ colspan: '4' }
							- if @reservation.payment == 1
								Tarjeta de crédito
							- elsif @reservation.payment == 2
								Depósito o Transferencia
							- else 
								Efectivo
					%tr
						%th{ colspan: '4' }
							= t("model.#{controller_name.singularize}.attributes.observations")
					%tr
						%td{ colspan: '4' }
							= @reservation.observations.blank? ? "N/A" : @reservation.observations
					%tr
						%th{ colspan: '1' } 
							Habitación
						%th{ colspan: '1' } 
							Cantidad
						%th{ colspan: '2' } 
							Precio
					%tr
						- @reservation.orders.each do |item|
							%tr
								%td{ colspan: '1'}
									= item.room.name
								%td{ colspan: '1'}
									= item.quantity
								%td{ colspan: '2'}
									= number_to_currency(item.room.price, precision: 2, format: "%u %n", unit: "Bs.")
					%tr
						%th{ colspan: '3' } 
							Total por noche
						%th.red.lighten-5{ colspan: '1' }
							= number_to_currency(@reservation.total_price_for_night, precision: 2, format: "%u %n", unit: "Bs.")
							
					%tr
						%th{ colspan: '3' } 
							Total por estadía
						%th.blue.lighten-5{ colspan: '1' }
							= number_to_currency(@reservation.price_total, precision: 2, format: "%u %n", unit: "Bs.")

app/views/reservations/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@reservation.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");